CREATE DATABASE IF NOT EXISTS `GENESYS_INTERVIEW` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
-- DROP TABLE IF EXISTS `GENESYS_INTERVIEW`.`WEATHER_METRIC`;
-- DROP TABLE IF EXISTS `GENESYS_INTERVIEW`.`SENSOR`;

CREATE TABLE IF NOT EXISTS `GENESYS_INTERVIEW`.`SENSOR` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(128) NOT NULL,
    CONSTRAINT PK_SENSOR PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='Sensor Information';

CREATE TABLE IF NOT EXISTS `GENESYS_INTERVIEW`.`WEATHER_METRIC` (
    `ID` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `SENSOR_ID` BIGINT UNSIGNED,
    `EVENT_TIMESTAMP` DATETIME NOT NULL COMMENT 'The timestamp for the event',
    `TEMPERATURE` INT DEFAULT NULL COMMENT 'The reported temperature.',
    `HUMIDITY` TINYINT UNSIGNED DEFAULT NULL COMMENT 'The reported humidity. Specified as an integer that represents the percentage.',
    `WIND_SPEED` INT UNSIGNED DEFAULT NULL COMMENT 'The representation of the wind speed. Metric or Imperial is configured in the sensor.',
    `WIND_DIRECTION` VARCHAR(32) DEFAULT NULL,
    `CLOUD_COVER` VARCHAR(32) DEFAULT NULL,
    CONSTRAINT PK_WEATHER_METRIC PRIMARY KEY (ID),
    CONSTRAINT FK_SENSOR FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(ID),
    INDEX IDX_EVENT_TIMESTAMP (EVENT_TIMESTAMP)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='A representation of an sensor metrics from sensors.. Original model name - SensorMetric.';
